version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9.4
        environment:
          JOBS: 1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Installing yarn
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Running Tests
          command: yarn run test

  codacy:
    docker:
      - image: circleci/node:8.9.4
        environment:
          JOBS: 1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Installing yarn
          command: yarn install
      - run:
          name: Installing Codacy
          command: yarn add codacy-coverage --save
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Sending Coverage Data to Codacy
          command: yarn run codacy

workflows:
  version: 2
  test-codacy:
    jobs:
      - test
      - codacy:
          requires:
            - test